apiVersion: tenantoperator.stakater.com/v1beta1
kind: Tenant
metadata:
  name: gabbar
spec:
  owners:
   users:
   - rasheed@stakter.com
   groups:
   - stakater-stage-dominator-owner
  quota: nordmart-medium
  argocd:
    sourceRepos:
      - 'https://github.com/stakater/nordmart-infra-gitops-config'
      - 'https://github.com/stakater/nordmart-apps-gitops-config'
      - 'https://nexus-helm-stakater-nexus.apps.stage.2cc6dtsv.kubeapp.cloud/repository/helm-charts/'
  templateInstances:
  - spec:
      template: tenant-vault-access
      sync: true
  namespaces:
  - stage
  - prod
