apiVersion: tenantoperator.stakater.com/v1beta1
kind: Tenant
metadata:
  name: veeru
spec:
  owners:
   users:
   - hanzala@stakater.com
   - osama@stakater.com
  quota: nordmart-medium
  argocd:
    sourceRepos:
      - 'https://github.com/stakater/nordmart-apps-gitops-config'
      - 'https://github.com/stakater/nordmart-infra-gitops-config'
      - 'https://nexus-helm-stakater-nexus.apps.stage.2cc6dtsv.kubeapp.cloud/repository/helm-charts/'
  templateInstances:
  - spec:
      template: tenant-vault-access
      sync: true
  namespaces:
  - build
  - stage
  - prod
  specificMetadata:
    - namespaces:
        - veeru-build
      annotations:
        openshift.io/node-selector: node-role.kubernetes.io/pipeline=
