apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: stakater-gitlab-instance
spec:
  chart:
    version: "6.3.2" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/0.11.3/CHART_VERSIONS
    values:
      # Disable NGINX Ingress Controller.
      nginx-ingress:
        enabled: false
      global:
        # Configure the domain from the previous step.
        hosts:
          domain: apps.devtest.vxdqgl7u.kubeapp.cloud
        ingress:
          configureCertmanager: false
          tls:
            secretName: default-tls-cert
          # Unset `spec.ingressClassName` on the Ingress objects
          # so the OpenShift Router takes ownership.
          class: none
          annotations:
            # The OpenShift documentation says "edge" is the default, but
            # the TLS configuration is only passed to the Route if this annotation
            # is manually set.
            route.openshift.io/termination: "edge"
        appConfig:
          omniauth:
            enabled: true
            autoSignInWithProvider: 'saml'
            allowSingleSignOn: [saml]
            blockAutoCreatedUsers: false
            autoLinkSamlUser: true
            autoLinkUser: ['saml']
            providers:
            - secret: saml-provider
              key: provider
