apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-instance
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitlab-instance
    server: 'https://kubernetes.default.svc'
  source:
    path: dev-test/gitlab-instance
    repoURL: 'https://github.com/stakater/nordmart-infra-gitops-config.git'
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
