apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-instance
  namespace: openshift-gitops
spec:
  destination:
    namespace: mattermost-instance
    server: 'https://kubernetes.default.svc'
  source:
    chart: mattermost-instance
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 0.1.7
    helm:
      releaseName: mattermost-instance
      values: |
        tenant:
          database:
            connectionString: AgBYOVp7GEM7IAil+xkU2lTiY09Yu0OZiE6ajfneCctddEjRjMSoSHevkiTLBBDbApY9QEibL8ZzHjPSlc+hZ1LN5gU2QUx9150vbzuaPGaXk5wF8opM1SixtdtP5NNj1jGOCL8cuBWygEQzEgESej7DXJ2wMqotkcdts/pynzc+Hx8jHwTpn4bf7GAO2nfLnSUvLFX1nUC92COTwI44HoWkbOVxiAJ3Vt1taQrzHKkX1CVnucplbrMx4lI+tdOKBRID4wnSnSxdnLgSouBnOT3021KRAmh1aaSqcmR8J3VGOef8snkoAvDgdv0331oEfwq/jZACMTMMqDr8V7lj7BeK+q8D4m4Zdr5Za4/4gjh+IPr7EYAGgmr6YJw1kpzURryHMzobcJ/aWy/ij4gYOf3Skh9yZeIgN/AqSa1GYQMlGhIGU7kM3HuK0Mpvf3Ulwqu61F52wbQWYlDJFOZ/kYmvInrugAOAuKMKEgorjUEKhXjpRnNXxaz2a+6xwNCANwwqkMtR9TeEbt6q/hXjdQs3gRaXHzwPR61LW7rM4UxelePF9i5bdSsAfmcSNn7OxdXvG/GkKiwT4pRr1rf0CuXIi3//occclRnFM+bkKlGze2zb5tCoi1Ok3RyRS0vNPJsXGkMJcru8y+ipTXqMoz2xuk+4FJNsIEO+te3WvDQqpwDB72b/Hfaw84s3qIrcHGEjtSyC4jo1TLdpgC5MbEwZK3pXZogtmpHQ+cCEhqFi0DLKKMt2tZ4JM3TkNZwvZjlVlCjbLDWWvwdIFBUJtBIW5oECs1vVtxDREmhlG+wHJxG7EZwMYJHhMFt4Z9oG0Hc1Jixj2XCKN+Fcbs8+GDXTnso3yU0VfrsXJRmRemshAlivcQ==
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
