apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-instance
  namespace: openshift-gitops
spec:
  destination:
    namespace: mattermost-instance
    server: 'https://kubernetes.default.svc'
  source:
    chart: mattermost-instance
    repoURL: https://stakater.github.io/stakater/charts
    targetRevision: 0.1.9
    helm:
      releaseName: mattermost-instance
      values: |
        tenant:
          database:
            connectionString: cG9zdGdyZXM6Ly9kb2N1bWVudHNlcnZpY2UtdXNlcjpSd0coT1QyPFZ3dTE7XyltfFVkbHdDbXZAcG9zdGdyZXMtcHJpbWFyeS5tYXR0ZXJtb3N0LWluc3RhbmNlLnN2Yzo1NDMyL2RvY3VtZW50c2VydmljZS1kYg==
          forecastle:
            icon: https://github.com/stakater/ForecastleIcons/raw/master/alert-manager.png
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
