apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-instance
  namespace: openshift-gitops
spec:
  destination:
    namespace: mattermost-instance
    server: 'https://kubernetes.default.svc'
  source:
    chart: mattermost-instance
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 0.1.16
    helm:
      releaseName: mattermost-instance
      values: |
        tenant:
          database:
            connectionString: AgBDdlnoG5Hjp2aVpRuPW1xDReu2C6a2w/AXkyTCmmlB9kK9+d8TTcmi8PI7o3BI2GoZqGabQYsGVOUZRnVKg7VBBAAKaztSBmNOND3q5AdHfso5GfijLtldYYzVpiYTdVzLwQV+zSpnF7syOh2w3fGf8HWHBj2suIZL7SddUBNs0YOb9680Ggy9Q5NGP9VZTV8GZTgLCe0vaMSPFsA/ykQGVQ0MKF+tvNLP+fRKGzwFCZYkAYeX1TFqkLxTmnGxyNnt1GUCOeTKtEJHKnYPbGqYFQvYYgfxvbNhr0+ltBApz0RV2TxEzEnr0TYYlqMtMJJsjK67SORHW0iznEKkhBunZuhgT/6MSTuvpqARmGGRtxui1PcbeR3QGN1X//ZdE3dT2Vul4W3uNToDKhsYqX0oJ73nMIw37cojjFl/nNlJVvrz9Eh05PAm2OpC36wucA412KG19flkmo04H4/bTxEZaXQVSZoADPaGTFAgcGVcfFC9H6lEr9j2huviyxg1rniUN6O+NXclNNLEax6lnpMHwvQd5KfB4Rwa5ANMeoRTqTgDMxN7mJruGIgp0r30a3qDFUGncr6tKU54J4Ec2Odxz2RdANlqn/Dn6U0fsAlxA8uWbGC71e+FiOS20gg2VNOaB7mruYNmJERhSVunvBm9xAf4Kl243etxrIoX8AJx53ZM9Xmp8F03VdE2xdv1QqDWDPNDn7DQeTfAyZz5VdO8g/Qfm6R3DQPKQQRemRhiKT08PbPL4RKvzmzz0ie6GZHR1TC2Hd6uIMP96A437Iwe6bGMzMpa8kPIVx+L07gEZbN+nnz/v0GhgMWtl8ssbeSVGfR7aiV4aLsUg/yIo+HqXdEfWF+ol+893kSArxQmo0MAO+9p2g==
          forecastle:
            icon: https://github.com/stakater/ForecastleIcons/raw/master/alert-manager.png
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
