apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-instance
  namespace: openshift-gitops
spec:
  destination:
    namespace: mattermost-instance
    server: 'https://kubernetes.default.svc'
  source:
    chart: mattermost-instance
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 0.1.7
    helm:
      releaseName: mattermost-instance
      values: |
        tenant:
          database:
            connectionString: AgCVR3v8mfbH1nbK0pQ6wsuy116qRR6XdRCEcm79LZpFFMN9ZtObOQiYcsOMIXomr/NA5Jtu+UKeffp1dFBLqgmErqY1R+TsLQDSNTpAzpFDChvzr6/pVbHpatRIeW3N/MZRqLJLO9uj47Hk3hUGNpcHn6h+ygM+ECC1RSx1VltsHz/hHnxAQ9hJHQwzEs4uD/PJpZGLPmY3MqVv/JxqLbwBhB/wsuh9neXwKl6XQuuiSDd1tZ6feoTUlYB9L2pYtFZ9XHRx5NeC+UKSnNsdEKmv2fJHIPACENChNnakE5asKwXaGb/gKnK2Os+42WUu4wcdq4wyms31B4MQbIpfC87Phe9vBXKBGagxKyKpMTo2hns3cpv/0SKmPGMFs0bdyTsY8cPis/Zzu8dxBRbzl0vKY1FSrmVNs2p8Rh1rAmXIGX4UNIuMRDBBqtz2yYdlv7lF8sg7ToVnoYL8q3iD+unU6h4HUdLxQckKERU8adRjnx1QbGTBIq9bXAdAKhvgilkgG5FBB3ZneuKWuwJNLGiqUNWTSUFNR+PLAJvb41pOjLog+BvsZn0DyJqtGQpeHPNMhLszsExjKZyWX1Pm0yZWec/HfVi9RQ3L0syopk+gcYCm915eG4KwQnW7KE+GbzDU/HM1AHRpTz/CZKbxe0+rgyK2BTR1Vy9oyAFjJaoCz3pBW5pfyllkv/dwPoLrn9T84fuCptrHuqYHjxUOqUNy/WoNKdo4SmRLm/hPze08cuO/DI78R4GsijMUhg94Bw0q+0Q5C62MMSIFWhmJsb2VpTNOEP0hAU/jBPIQeJbp5PsE4JYO5M75XQiIlR7ultNSd6yMzaO/EXcU+2M6uZHQRob32pDI/iSUUc05fJm1Xft+1g==
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
