apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop-exercise
  namespace: openshift-gitops
spec:
  destination:
    namespace: workshop-exercise
    server: 'https://kubernetes.default.svc'
  source:
    chart: workshop-exercise
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 0.0.202
    helm:
      releaseName: workshop-exercise
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
