
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-operator-config
  namespace: rh-openshift-gitops-instance
spec:
  destination:
    namespace: rh-openshift-gitops-instance
    server: 'https://kubernetes.default.svc'
  source:
    path: sno8/tenant-operator-config
    repoURL: 'https://github.com/stakater-lab/webinar-infra-gitops-config.git'
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

