apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webinar-apps-gitops-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: argocd-apps/sno8
    repoURL: 'https://github.com/stakater-lab/webinar-apps-gitops-config'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
